// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMTPReceiver.Data;

#nullable disable

namespace SMTPReceiver.Migrations
{
    [DbContext(typeof(OneSourceContext))]
    [Migration("20240227150456_ChangedIsEnabledDataTypeToBoolInMappingSMTPReceiver")]
    partial class ChangedIsEnabledDataTypeToBoolInMappingSMTPReceiver
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMTPReceiver.Data.Entities.MappingSMTPReceiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<string>("ContainsString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("containsString");

                    b.Property<string>("DataAccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dataAccess");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DestinationInstance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("destinationInstance");

                    b.Property<string>("DiscardInternal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discardInternal");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("isEnabled");

                    b.Property<string>("MenuEntryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mode");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("section");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("toEmail");

                    b.HasKey("Id");

                    b.ToTable("sys_MappingSMTPReceiver");
                });

            modelBuilder.Entity("SMTPReceiver.Data.Entities.SMTPLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmlPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emlPath");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("isEnabled");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mode");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ruleName");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to");

                    b.HasKey("Id");

                    b.ToTable("sys_SMTPLog");
                });
#pragma warning restore 612, 618
        }
    }
}
